# -*- coding: utf-8 -*-
"""Shkurko_DA8.py

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1VlnQt9GJg2DuJqAGAoIFTebX6nC7hNK-
"""

#завантажимо необхідні бібліотеки
import streamlit as st
import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns
import altair as alt
import numpy as np
import plotly.express as px
from sklearn.linear_model import LinearRegression

df = pd.read_csv('data.csv')

df.info()
df.describe()

missing_data = df.isnull()
for column in missing_data.columns.values.tolist():
    print(column)
    print (missing_data[column].value_counts())
    print("")

st.set_page_config(
    page_title="Економічні показники країн за 2019-2023 роки",
    page_icon="🌎",
    layout="wide",
    initial_sidebar_state="expanded",
    menu_items={
        'Get Help': 'https://docs.streamlit.io/',
        'Report a bug': 'https://github.com/streamlit/streamlit/issues',
        'About': 'Інтерактивна панель для аналізу економічних показників країн'
    }
)

st.sidebar.title("Панель фільтрації")

selected_year = st.sidebar.selectbox("Рік", sorted(df["Year"].unique()))
selected_region = st.sidebar.multiselect("Регіон", df["Region"].unique(), default=df["Region"].unique())
selected_сountry = st.sidebar.multiselect("Країна", df["Country Name"].unique(), default=df["Country Name"].unique())

selected_max_population = st.sidebar.slider(
    "Кількість населення",
    min_value=int(df["Population"].min()),
    max_value=int(df["Population"].max()),
    value=int(df["Population"].max()),
    step=100000
)

show_map = st.sidebar.checkbox("Показати мапу світу")

# Перемикач графіків
chart_option = st.sidebar.radio(
    "📊 Оберіть графік для перегляду:",
    [
        "Експорт країни vs Імпорт",
        "Boxplot кількості населення по регіонам",
        "Scatter: ВВП vs Експорт",
        "Теплова карта кореляцій"
    ]
)

# Фільтрація

df_filtered = df[
    (df["Year"] == selected_year) &
    (df["Region"].isin(selected_region)) &
    (df["Country Name"].isin(selected_сountry)) &
    (df["Population"] <= selected_max_population)
]

st.sidebar.markdown("Побудова регресії")
numeric_columns = df_filtered.select_dtypes(include=np.number).columns.tolist()

reg_x = st.sidebar.selectbox("Оберіть змінну X", numeric_columns, index=0)
reg_y = st.sidebar.selectbox("Оберіть змінну Y", numeric_columns, index=1)
show_regression = st.sidebar.checkbox("Показати регресійну модель")


# Інформаційний блок
st.sidebar.markdown("---")
st.sidebar.markdown(" **Інструкція**: \nВ даній роботі надано інформацію щодо кількості населення, ВВП , експорту та імпорту 15 країн світу. Для аналізу фільтруйте дані за параметрами і переглядайте графіки та таблиці на панелі праворуч.")
st.sidebar.markdown(" **Автор**: Шкурко Вероніка")

# Фільтрація

df_filtered = df[
    (df["Year"] == selected_year) &
    (df["Region"].isin(selected_region)) &
    (df["Country Name"].isin(selected_сountry)) &
    (df["Population"] <= selected_max_population)
]


# Основна панель

st.title("🌎 Економічний дашборд країн")
st.subheader(f"🔍 Відфільтровано {df_filtered.shape[0]} країн")

# Кнопка завантаження CSV
csv = df_filtered.to_csv(index=False).encode("utf-8")
st.download_button(
    label="⬇️ Завантажити CSV",
    data=csv,
    file_name="data.csv",
    mime="text/csv"
)

# Інтерактивна таблиця результатів

st.subheader("Оберіть, які стовпці таблиці відображати")

# Отримання всіх назв стовпців
all_columns = df_filtered.columns.tolist()
default_columns = ["Country Name", "Region", "GDP (current US$)"]

selected_columns = st.multiselect(
    "Оберіть стовпці для перегляду:",
    options=all_columns,
    default=[col for col in default_columns if col in all_columns]
)

if selected_columns:
    st.dataframe(df_filtered[selected_columns])
else:
    st.info("Оберіть хоча б один стовпець, щоб побачити таблицю.")


# Карта країн
if show_map:
    st.subheader("Географія країн")

    map_data = df_filtered[["Latitude", "Longitude"]].dropna().rename(
        columns={"Latitude": "latitude", "Longitude": "longitude"}
    )

    if not map_data.empty:
        st.map(map_data)
    else:
        st.warning("Немає доступних координат для побудови карти.")



# Відображення обраного графіка

if chart_option == "Експорт країни vs Імпорт":
    st.subheader("📊 Експорт країни vs Імпорт")
    chart = alt.Chart(df_filtered).mark_circle(size=60).encode(
        x='Exports',
        y='Imports',
        color='Region:N',
        tooltip=['Country Name', 'Exports', 'Imports', 'Region']
    ).interactive().properties(title="Експорт країни vs Імпорт")
    st.altair_chart(chart, use_container_width=True)

elif chart_option == "Boxplot кількості населення по регіонам":
    st.subheader("📊 Boxplot кількості населення по регіонам")
    fig, ax = plt.subplots(figsize=(10, 5))
    sns.boxplot(data=df_filtered, x="Region", y="Population", ax=ax)
    ax.set_title("Розподіл кількості населення по регіонам")
    st.pyplot(fig)

elif chart_option == "Scatter: ВВП vs Експорт":
    st.subheader("📊 Scatter: ВВП vs Експорт")
    chart = alt.Chart(df_filtered).mark_circle(size=60).encode(
        x='GDP',
        y='Exports',
        color='Region',
        tooltip=['Country Name', 'GDP', 'Exports']
    ).interactive().properties(title="ВВП vs Експорт")
    st.altair_chart(chart, use_container_width=True)

elif chart_option == "Теплова карта кореляцій":
    st.subheader("📊 Теплова карта кореляцій")
    numeric_cols = df_filtered.select_dtypes(include=[np.number])
    corr = numeric_cols.corr()
    fig, ax = plt.subplots(figsize=(7, 5))
    sns.heatmap(corr, annot=True, cmap='coolwarm', fmt=".2f", ax=ax)
    ax.set_title("Кореляційна матриця числових показників")
    st.pyplot(fig)

# Побудова регресійної моделі
if show_regression:
    st.subheader(f"📈 Лінійна регресія: {reg_y} ~ {reg_x}")

    df_reg = df_filtered[[reg_x, reg_y]].dropna()

    if df_reg.shape[0] >= 2:
        model = LinearRegression()
        model.fit(df_reg[[reg_x]], df_reg[reg_y])
        y_pred = model.predict(df_reg[[reg_x]])

        coef = model.coef_[0]
        intercept = model.intercept_
        r2 = model.score(df_reg[[reg_x]], df_reg[reg_y])

        st.markdown(f"**Коефіцієнт нахилу (β):** {coef:.4f}")
        st.markdown(f"**Зсув (intercept):** {intercept:.4f}")
        st.markdown(f"**R²:** {r2:.4f}")

        fig, ax = plt.subplots(figsize=(8, 5))
        sns.scatterplot(data=df_reg, x=reg_x, y=reg_y, ax=ax)
        sns.lineplot(x=df_reg[reg_x], y=y_pred, color='red', ax=ax)
        ax.set_title(f"Регресія {reg_y} ~ {reg_x}")
        st.pyplot(fig)
    else:
        st.warning("Недостатньо даних для побудови регресії.")